### ISSUE TITLE
Padding disappears on some window width

### ISSUE THREAD

**Issue by edjafarov** [openconf/jschat#73] opened 2014-02-07 06:30 UTC
![screen shot 2014-02-07 at 08 29 44](https://f.cloud.github.com/assets/509978/2107163/44bc161c-8fc1-11e3-81c0-55d93a6efc87.png)

**Comment by sejoker** [comment] 2014-05-08 10:38
Can't reproduce in chrome, firefox.

**Comment by sudodoki** [comment] 2014-05-08 10:42
If I recall correctly, it was fixed via https://github.com/openconf/jschat/commit/bc0840f9a8b57c5264fb445fae04dc889e7d9d4d.

**Closed as completed by sudodoki** 2014-05-08 10:42 UTC
Labels: bug

**Comment by sudodoki** [comment] 2014-05-08 14:51
@sejoker thanks for bringing this up.
